//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neusoft.CCS.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActionInfo
    {
        public ActionInfo()
        {
            this.ProcessDetails = new HashSet<ProcessDetail>();
        }
    
        public int actionID { get; set; }
        public int flowID { get; set; }
        public string actionName { get; set; }
        public System.DateTime createDate { get; set; }
        public Nullable<System.DateTime> modifyDate { get; set; }
        public string createEmpID { get; set; }
        public string modifyEmpID { get; set; }
        public int orderNo { get; set; }
        public bool available { get; set; }
        public int stepRepeatNo { get; set; }
        public int stepType { get; set; }
        public bool isMulty { get; set; }
        public bool isLast { get; set; }
        public string prefixActionIDs { get; set; }
        public Nullable<int> actionVersion { get; set; }
    
        public virtual FlowInfo FlowInfo { get; set; }
        public virtual ICollection<ProcessDetail> ProcessDetails { get; set; }
    }
}
