//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neusoft.CCS.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Business
    {
        public Business()
        {
            this.ComplaintInfoes = new HashSet<ComplaintInfo>();
            this.Departments = new HashSet<Department>();
            this.Staffs = new HashSet<Staff>();
        }
    
        public int BussinessID { get; set; }
        public string BussinessName { get; set; }
        public string BussinessDescribe { get; set; }
    
        public virtual ICollection<ComplaintInfo> ComplaintInfoes { get; set; }
        public virtual ICollection<Department> Departments { get; set; }
        public virtual ICollection<Staff> Staffs { get; set; }
    }
}
