//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neusoft.CCS.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaseInfo
    {
        public CaseInfo()
        {
            this.ComplaintDisposeAndFeedbackInfoes = new HashSet<ComplaintDisposeAndFeedbackInfo>();
            this.ComplaintInfoes = new HashSet<ComplaintInfo>();
            this.ComplaintReturnVisitInfoes = new HashSet<ComplaintReturnVisitInfo>();
            this.Histories = new HashSet<History>();
            this.ImportantEvent_Center = new HashSet<ImportantEvent_Center>();
            this.ImportantEvent_Staff = new HashSet<ImportantEvent_Staff>();
            this.ImportantEvent_Department = new HashSet<ImportantEvent_Department>();
            this.ProcessDetails = new HashSet<ProcessDetail>();
        }
    
        public int ID { get; set; }
        public int Com_ID { get; set; }
        public Nullable<System.DateTime> ArchiveDate { get; set; }
        public int State { get; set; }
    
        public virtual Complainer Complainer { get; set; }
        public virtual ICollection<ComplaintDisposeAndFeedbackInfo> ComplaintDisposeAndFeedbackInfoes { get; set; }
        public virtual ICollection<ComplaintInfo> ComplaintInfoes { get; set; }
        public virtual ICollection<ComplaintReturnVisitInfo> ComplaintReturnVisitInfoes { get; set; }
        public virtual ICollection<History> Histories { get; set; }
        public virtual ICollection<ImportantEvent_Center> ImportantEvent_Center { get; set; }
        public virtual ICollection<ImportantEvent_Staff> ImportantEvent_Staff { get; set; }
        public virtual ICollection<ImportantEvent_Department> ImportantEvent_Department { get; set; }
        public virtual ICollection<ProcessDetail> ProcessDetails { get; set; }
    }
}
