//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neusoft.CCS.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComplaintInfo
    {
        public int Cpt_InfoID { get; set; }
        public int ID { get; set; }
        public Nullable<int> BussinessID { get; set; }
        public string Cpt_Way { get; set; }
        public System.DateTime Cpt_Date { get; set; }
        public string Cpt_Area { get; set; }
        public string Cpt_Class { get; set; }
        public string Cpt_Describe { get; set; }
        public Nullable<System.DateTime> Cpt_BeginTime { get; set; }
        public Nullable<System.DateTime> Cpt_EndTime { get; set; }
        public string Cpt_Comment { get; set; }
    
        public virtual Business Business { get; set; }
        public virtual CaseInfo CaseInfo { get; set; }
    }
}
