//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neusoft.CCS.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComplaintInfo
    {
        public int Cpt_InfoID { get; set; }
        public int ID { get; set; }
        public Nullable<int> BussinessID { get; set; }
        public string Cpt_Way { get; set; }
        public System.DateTime Cpt_Date { get; set; }
        public string Cpt_Area { get; set; }
        public string Cpt_Class { get; set; }
        public string Cpt_Describe { get; set; }
        public System.DateTime Cpt_BeginTime { get; set; }
        public System.DateTime Cpt_EndTime { get; set; }
    
        public virtual Business Business { get; set; }
        public virtual CaseInfo CaseInfo { get; set; }
    }
}
