//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neusoft.CCS.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComplaintDisposeAndFeedbackInfo
    {
        public int CptDF_ID { get; set; }
        public string Stf_ID { get; set; }
        public int ID { get; set; }
        public string CptDF_Solution { get; set; }
        public string CptDF_Content { get; set; }
        public Nullable<int> CptDF_Satisfaction { get; set; }
        public Nullable<System.DateTime> CptDF_BeginTime { get; set; }
        public Nullable<System.DateTime> CptDF_EndTime { get; set; }
    
        public virtual CaseInfo CaseInfo { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
