//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neusoft.CCS.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComplaintDisposeAndFeedbackInfo
    {
        public int CptDF_ID { get; set; }
        public string Stf_ID { get; set; }
        public int ID { get; set; }
        public string CptDF_Solution { get; set; }
        public string CptDF_Content { get; set; }
        public Nullable<int> CptDF_Satisfaction { get; set; }
        public Nullable<System.DateTime> CptDF_BeginTime { get; set; }
        public Nullable<System.DateTime> CptDF_EndTime { get; set; }
    
        public virtual CaseInfo CaseInfo { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
