//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neusoft.CCS.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public Department()
        {
            this.Companies = new HashSet<Company>();
        }
    
        public int DepartmentID { get; set; }
        public int BussinessID { get; set; }
        public string DepartmentName { get; set; }
        public string Describe { get; set; }
        public string DepartmentPhoneNum { get; set; }
        public string DepartmentRemark { get; set; }
    
        public virtual Business Business { get; set; }
        public virtual ICollection<Company> Companies { get; set; }
    }
}
