//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neusoft.CCS.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlowInfo
    {
        public FlowInfo()
        {
            this.ActionInfoes = new HashSet<ActionInfo>();
        }
    
        public int flowID { get; set; }
        public string flowName { get; set; }
        public System.DateTime createDate { get; set; }
        public Nullable<System.DateTime> modifyDate { get; set; }
        public string createEmpID { get; set; }
        public string modifyEmpID { get; set; }
        public int orderNo { get; set; }
        public bool available { get; set; }
    
        public virtual ICollection<ActionInfo> ActionInfoes { get; set; }
    }
}
