//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neusoft.CCS.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public int History_ID { get; set; }
        public Nullable<int> ID { get; set; }
        public string Stf_ID { get; set; }
        public string History_Process { get; set; }
        public System.DateTime History_HandleTime { get; set; }
    
        public virtual CaseInfo CaseInfo { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
