//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neusoft.CCS.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportantEvent_Department
    {
        public ImportantEvent_Department()
        {
            this.ImportantEvent_Staff = new HashSet<ImportantEvent_Staff>();
        }
    
        public int IptEvt_D_ID { get; set; }
        public string Stf_ID { get; set; }
        public int IptEvt_C_ID { get; set; }
        public int ID { get; set; }
        public string IptEvt_D_Duty { get; set; }
        public string IptEvt_D_Conclusion { get; set; }
        public System.DateTime IptEvt_D_BeginTime { get; set; }
        public System.DateTime IptEvt_D_EndTime { get; set; }
    
        public virtual CaseInfo CaseInfo { get; set; }
        public virtual ImportantEvent_Center ImportantEvent_Center { get; set; }
        public virtual ICollection<ImportantEvent_Staff> ImportantEvent_Staff { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
