//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neusoft.CCS.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportantEvent_Center
    {
        public ImportantEvent_Center()
        {
            this.CaseInfoes = new HashSet<CaseInfo>();
            this.ImportantEvent_Department = new HashSet<ImportantEvent_Department>();
        }
    
        public int IptEvt_C_ID { get; set; }
        public string Stf_ID { get; set; }
        public int ID { get; set; }
        public string IptEvt_C_Solution { get; set; }
        public System.DateTime IptEvt_C_BeginDate { get; set; }
        public System.DateTime IptEvt_C_EndDate { get; set; }
        public string IptEvt_C_Conclusion { get; set; }
    
        public virtual ICollection<CaseInfo> CaseInfoes { get; set; }
        public virtual CaseInfo CaseInfo { get; set; }
        public virtual ICollection<ImportantEvent_Department> ImportantEvent_Department { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
