//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neusoft.CCS.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportantEvent_Staff
    {
        public int IptEvt_S_ID { get; set; }
        public string Stf_ID { get; set; }
        public int ID { get; set; }
        public int IptEvt_D_ID { get; set; }
        public string IptEvt_S_Content { get; set; }
        public Nullable<System.DateTime> IptEvt_S_BeginTime { get; set; }
        public Nullable<System.DateTime> IptEvt_S_EndTime { get; set; }
    
        public virtual CaseInfo CaseInfo { get; set; }
        public virtual ImportantEvent_Department ImportantEvent_Department { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
