//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neusoft.CCS.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportantEvent_Staff
    {
        public int IptEvt_S_ID { get; set; }
        public string Stf_ID { get; set; }
        public int ID { get; set; }
        public int IptEvt_D_ID { get; set; }
        public string IptEvt_S_Content { get; set; }
        public Nullable<System.DateTime> IptEvt_S_BeginTime { get; set; }
        public Nullable<System.DateTime> IptEvt_S_EndTime { get; set; }
    
        public virtual CaseInfo CaseInfo { get; set; }
        public virtual ImportantEvent_Department ImportantEvent_Department { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
