//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neusoft.CCS.Repository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NeusoftCCSEntities : DbContext
    {
        public NeusoftCCSEntities()
            : base("name=NeusoftCCSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Business> Businesses { get; set; }
        public DbSet<CaseInfo> CaseInfoes { get; set; }
        public DbSet<Company> Companies { get; set; }
        public DbSet<Complainer> Complainers { get; set; }
        public DbSet<ComplaintDisposeAndFeedbackInfo> ComplaintDisposeAndFeedbackInfoes { get; set; }
        public DbSet<ComplaintInfo> ComplaintInfoes { get; set; }
        public DbSet<ComplaintReturnVisitInfo> ComplaintReturnVisitInfoes { get; set; }
        public DbSet<Department> Departments { get; set; }
        public DbSet<History> Histories { get; set; }
        public DbSet<ImportantEvent_Center> ImportantEvent_Center { get; set; }
        public DbSet<ImportantEvent_Department> ImportantEvent_Department { get; set; }
        public DbSet<ImportantEvent_Staff> ImportantEvent_Staff { get; set; }
        public DbSet<Position> Positions { get; set; }
        public DbSet<Staff> Staffs { get; set; }
        public DbSet<ActionInfo> ActionInfoes { get; set; }
        public DbSet<FlowInfo> FlowInfoes { get; set; }
        public DbSet<ProcessDetail> ProcessDetails { get; set; }
    }
}
