//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neusoft.CCS.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permission
    {
        public Permission()
        {
            this.Positions = new HashSet<Position>();
        }
    
        public int PermissionID { get; set; }
        public string PermissionDisplayName { get; set; }
        public string PermissionActionName { get; set; }
        public string PermissionControllerName { get; set; }
        public string PermissionCategory { get; set; }
    
        public virtual ICollection<Position> Positions { get; set; }
    }
}
