//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neusoft.CCS.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Position
    {
        public Position()
        {
            this.Staffs = new HashSet<Staff>();
        }
    
        public int Post_ID { get; set; }
        public string Post_Name { get; set; }
        public string Post_Content { get; set; }
        public string Post_Remark { get; set; }
        public Nullable<int> Post_SuperiorID { get; set; }
    
        public virtual ICollection<Staff> Staffs { get; set; }
    }
}
