//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neusoft.CCS.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Position
    {
        public Position()
        {
            this.Staffs = new HashSet<Staff>();
        }
    
        public int Post_ID { get; set; }
        public string Post_Name { get; set; }
        public string Post_Content { get; set; }
        public string Post_Remark { get; set; }
        public Nullable<int> Post_SuperiorID { get; set; }
    
        public virtual ICollection<Staff> Staffs { get; set; }
    }
}
