//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neusoft.CCS.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcessDetail
    {
        public int processID { get; set; }
        public int actionID { get; set; }
        public int ID { get; set; }
        public string processEmpID { get; set; }
        public string processNote { get; set; }
        public string processRoleID { get; set; }
        public bool isDone { get; set; }
        public System.DateTime createDate { get; set; }
        public Nullable<System.DateTime> finishDate { get; set; }
        public bool isLast { get; set; }
        public bool isRollBack { get; set; }
    
        public virtual CaseInfo CaseInfo { get; set; }
        public virtual ActionInfo ActionInfo { get; set; }
    }
}
