//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neusoft.CCS.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public Staff()
        {
            this.ComplaintDisposeAndFeedbackInfoes = new HashSet<ComplaintDisposeAndFeedbackInfo>();
            this.ComplaintReturnVisitInfoes = new HashSet<ComplaintReturnVisitInfo>();
            this.Histories = new HashSet<History>();
            this.ImportantEvent_Center = new HashSet<ImportantEvent_Center>();
            this.ImportantEvent_Department = new HashSet<ImportantEvent_Department>();
            this.ImportantEvent_Staff = new HashSet<ImportantEvent_Staff>();
        }
    
        public string Stf_ID { get; set; }
        public Nullable<int> BussinessID { get; set; }
        public Nullable<int> Post_ID { get; set; }
        public string Stf_Name { get; set; }
        public bool Stf_Gender { get; set; }
        public int Stf_Age { get; set; }
        public string Stf_IdentifyCardNum { get; set; }
        public System.DateTime Stf_EntryTime { get; set; }
    
        public virtual Business Business { get; set; }
        public virtual ICollection<ComplaintDisposeAndFeedbackInfo> ComplaintDisposeAndFeedbackInfoes { get; set; }
        public virtual ICollection<ComplaintReturnVisitInfo> ComplaintReturnVisitInfoes { get; set; }
        public virtual ICollection<History> Histories { get; set; }
        public virtual ICollection<ImportantEvent_Center> ImportantEvent_Center { get; set; }
        public virtual ICollection<ImportantEvent_Department> ImportantEvent_Department { get; set; }
        public virtual ICollection<ImportantEvent_Staff> ImportantEvent_Staff { get; set; }
        public virtual Position Position { get; set; }
    }
}
